### ISSUE TITLE
Add commands

### ISSUE THREAD

**Issue by miekg** [miekg/dreck#54]
Currently the /integration command in CoreDNS is handled by `webhook` and `jq` and some scripts. It reports status back etc. We can probably integrate this into dreck by allowing commands.

This also allows us to implement /release (TODO: link coredns issue) with relative easy.

Some open questions: 
* what parameters should we give the command?
* gather stderr output and return that in the status? (can that be done?)
* use exit code for success or failures?

**Comment by miekg** [comment]
/cc @chrisohaver
(our whole setup is working and I'm in no hurry to replace a functional system, so fyi. Longer term this might cut back on the amount of code we need to maintain).

**Comment by miekg** [comment]
OK, pushed to master you can now define commands.

Would be nice to add some context to them, I will check what used on drone. Might be as "easy" as giving it the url of the issue or pr

**Comment by chrisohaver** [comment]
Cool.👍

**Comment by miekg** [comment]
calling fixed. Will work on automating coredns release first.
